# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x13pulsarity.databsase\"\x19\n\tAttribute\x12\x0c\n\x04name\x18\x01 \x01(\t\"w\n\x05Pilot\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x18\n\x10\x64isplay_callsign\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x32\n\nattributes\x18\x04 \x03(\x0b\x32\x1e.pulsarity.databsase.Attribute\"4\n\x06Pilots\x12*\n\x06pilots\x18\x01 \x03(\x0b\x32\x1a.pulsarity.databsase.Pilot\"Y\n\tRaceEvent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x32\n\nattributes\x18\x03 \x03(\x0b\x32\x1e.pulsarity.databsase.Attribute\"<\n\nRaceEvents\x12.\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1e.pulsarity.databsase.RaceEvent\"Y\n\tRaceClass\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x32\n\nattributes\x18\x03 \x03(\x0b\x32\x1e.pulsarity.databsase.Attribute\"B\n\x0bRaceClasses\x12\x33\n\x0braceclasses\x18\x01 \x03(\x0b\x32\x1e.pulsarity.databsase.RaceClass\"Z\n\x05Round\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tround_num\x18\x02 \x01(\x05\x12\x32\n\nattributes\x18\x03 \x03(\x0b\x32\x1e.pulsarity.databsase.Attribute\"4\n\x06Rounds\x12*\n\x06rounds\x18\x01 \x03(\x0b\x32\x1a.pulsarity.databsase.Round\"X\n\x04Heat\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08heat_num\x18\x02 \x01(\x05\x12\x32\n\nattributes\x18\x03 \x03(\x0b\x32\x1e.pulsarity.databsase.Attribute\"1\n\x05Heats\x12(\n\x05heats\x18\x01 \x03(\x0b\x32\x19.pulsarity.databsase.Heatb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ATTRIBUTE._serialized_start=39
  _ATTRIBUTE._serialized_end=64
  _PILOT._serialized_start=66
  _PILOT._serialized_end=185
  _PILOTS._serialized_start=187
  _PILOTS._serialized_end=239
  _RACEEVENT._serialized_start=241
  _RACEEVENT._serialized_end=330
  _RACEEVENTS._serialized_start=332
  _RACEEVENTS._serialized_end=392
  _RACECLASS._serialized_start=394
  _RACECLASS._serialized_end=483
  _RACECLASSES._serialized_start=485
  _RACECLASSES._serialized_end=551
  _ROUND._serialized_start=553
  _ROUND._serialized_end=643
  _ROUNDS._serialized_start=645
  _ROUNDS._serialized_end=697
  _HEAT._serialized_start=699
  _HEAT._serialized_end=787
  _HEATS._serialized_start=789
  _HEATS._serialized_end=838
# @@protoc_insertion_point(module_scope)
