# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhttp.proto\x12\x0epulsarity.http\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"0\n\rLoginResponse\x12\x1f\n\x17password_reset_required\x18\x01 \x01(\x08\"B\n\x14ResetPasswordRequest\x12\x14\n\x0cold_password\x18\x01 \x01(\t\x12\x14\n\x0cnew_password\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'http_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSRESPONSE._serialized_start=30
  _STATUSRESPONSE._serialized_end=62
  _LOGINREQUEST._serialized_start=64
  _LOGINREQUEST._serialized_end=114
  _LOGINRESPONSE._serialized_start=116
  _LOGINRESPONSE._serialized_end=164
  _RESETPASSWORDREQUEST._serialized_start=166
  _RESETPASSWORDREQUEST._serialized_end=232
# @@protoc_insertion_point(module_scope)
