name: Backend-Tests

permissions:
  contents: read
  issues: read
  pull-requests: write
  checks: write

on:
  push:
    branches: [master]
    paths-ignore: ['docs/**', '*.md', '*.rst']
  pull_request:
    paths-ignore: [ 'docs/**', '*.md', '*.rst' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Test with tox
      run: uv run tox