name: Pylint

permissions:
  contents: read
  issues: read
  pull-requests: write
  checks: write

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --group dev
    
    - name: Analysing the code with pylint
      run: uv run pylint $(git ls-files 'src/pulsarity')
